version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["MindDepository/Dockerfile"]

[[analyzers]]
name = "csharp"

[[transformers]]
name = "dotnet-format"