name: Docker Image Build

on:
  pull_request:
    branches: ['dev']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt-get remove moby-containerd moby-runc -y
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install docker.io -y

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESSTOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        run: |
          echo "::set-output name=labels::type=raw,value=0.1.${{ github.run_number }},priority=1000,type=ref,event=branch,type=raw,value=latest"

      - name: Build and push
        run: |
          docker build -t pramudithapothuwila/hivevaultservice:${{ steps.meta.outputs.labels }} .
          docker push pramudithapothuwila/hivevaultservice:${{ steps.meta.outputs.labels }}
          docker tag pramudithapothuwila/hivevaultservice:${{ steps.meta.outputs.labels }} pramudithapothuwila/hivevaultservice:latest
          docker push pramudithapothuwila/hivevaultservice:latest