name: Docker Image Build

on:
  pull_request:
    branches: ['dev']


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ DOCKER_USERNAME }}
          password: ${{ DOCKER_ACCESSTOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{DOCKER_USERNAME }}/hivevaultservice
          tags: |
            type=raw,value=0.1.${{ github.run_number }},priority=1000
            type=ref,event=branch
            type=raw,value=latest
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hivevaultservice:${{ steps.vars.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/hivevaultservice:latest
          labels: ${{ steps.meta.outputs.labels }}

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact

      - name: Display structure of downloaded files
        run: ls -R
